server:
  port: 8085
  ssl:
    key-store: classpath:namph.jks
    key-store-password: password
    keyStoreType: PKCS12
    key-alias: namph

  security:
    require-ssl: true

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

mongo:
  remoteUri: "localhost:27017"

path :
  avatar: /avatar/
